Add VFX Class's
Yimura/GTAV-Classes pull request #13
Opened 2022-07-29 23:39 UTC by At0ms

All the vfx class's i have reversed so far, I can provide the sigs aswell if requested.

2022-07-30 21:40 UTC, Yimura requested changes
Where did you get the CVfx name? Is it somewhere in the game dumps or from somewhere in the game files?

Could you follow the same naming scheme as the other classes in this repo? Your class members don't start with `m_` and don't use `snake_casing`.

2022-07-30 21:40 UTC, Yimura commented on misc/CVfx.hpp
> +// Credit: At0ms/Andy
Add this at the top

2022-07-30 21:40 UTC, Yimura commented on misc/CVfx.hpp
> +    char pad_29CC[13952]; // 0x29CC
Is the CVFXTrain actually this big?

2022-07-30 21:47 UTC, At0ms commented
Hi

I will make the changes as requested.

And no the train class should not be that big i will redo that class.

2022-07-30 21:56 UTC, At0ms commented
> Where did you get the CVfx name? Is it somewhere in the game dumps or from somewhere in the game files?
> 
> Could you follow the same naming scheme as the other classes in this repo? Your class members don't start with `m_` and don't use `snake_casing`.

I found all the stuff i needed to reverse the vfx class's in this file visualsettings.dat found in the game rpfs
vfx is short for visualsettings but if you would like me to rename it to visualsettings i can

2022-07-30 21:56 UTC, Yimura commented
> > Where did you get the CVfx name? Is it somewhere in the game dumps or from somewhere in the game files?
> > Could you follow the same naming scheme as the other classes in this repo? Your class members don't start with `m_` and don't use `snake_casing`.
> 
> I found all the stuff i needed to reverse the vfx class's in this file visualsettings.dat found in the game rpfs vfx is short for visualsettings but if you would like me to rename it to visualsettings i can

Nah it's fine as is, I'd rather it be like that.

2022-08-19 13:14 UTC, At0ms commented
Making this a draft fornow as i never finished it.

2022-11-08 11:37 UTC, yasmasdas commented
I know this pr is old but may I have some signatures? @At0ms

2023-08-08 10:12 UTC, Yimura commented
Stale PR

2023-08-08 10:12 UTC, closed without merging