viewport
Yimura/GTAV-Classes pull request #166
Opened 2024-03-29 22:43 UTC by xiaoxiao921

2024-03-29 22:51 UTC, xiaoxiao921 commented
https://github.com/citizenfx/fivem/blob/1749be021ce2e3b9cf3fdc91d480399c8c0ce0e6/code/components/extra-natives-five/include/GamePrimitives.h#L115

2024-03-30 03:04 UTC, gir489returns approved these changes
FiveM totally didn't steal this from the leaked source or PDB, lmao.

2024-03-30 13:13 UTC, xiaoxiao921 commented
Yeah didn't realize but that's someone from fiveM pring it two weeks ago, so could be from leak...

2024-03-30 13:14 UTC, gir489returns commented
> Yeah didn't realize but that's someone from fiveM pring it two weeks ago, so could be from leak...

I mean, they work for Rockstar now, so someone from the FiveM team who works at Rockstar could've also updated it, so who knows.

2024-03-31 18:46 UTC, Yimura requested changes

2024-03-31 18:46 UTC, Yimura commented on graphics/CViewport.hpp
> +    grcViewport viewport;
`CViewportGame isn't part of the `rage` namespace, how is this able to compile? I'm guessing the headers haven't been added to the cpp test compile file...

2024-03-31 19:11 UTC, Yimura approved these changes

2024-03-31 19:11 UTC, merged